# Generated by Django 2.2.10 on 2021-12-16 15:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblAnswerOption',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255, verbose_name='вариант ответа')),
            ],
            options={
                'verbose_name': 'вариант ответа на вопрос',
                'verbose_name_plural': 'варианты ответов на вопросы',
            },
        ),
        migrations.CreateModel(
            name='TblParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='полное имя')),
            ],
            options={
                'verbose_name': 'участник опроса',
                'verbose_name_plural': 'участники опроса',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TblSurvey',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('survey_name', models.CharField(max_length=20, null=True)),
                ('survey_description', models.TextField()),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('finish_time', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'опрос',
                'verbose_name_plural': 'опросы',
            },
        ),
        migrations.CreateModel(
            name='TblQuestion',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('question_type', models.CharField(blank=True, choices=[('1', 'ответ текстом'), ('2', 'ответ с выбором одного варианта'), ('3', 'ответ с выбором нескольких вариантов')], max_length=50, null=True)),
                ('survey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey_service.TblSurvey')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='TblCompletedSurvey',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='survey_service.TblParticipant', verbose_name='участник')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='survey_service.TblSurvey', verbose_name='опрос')),
            ],
            options={
                'verbose_name': 'пройденный опрос',
                'verbose_name_plural': 'пройденные опросы',
                'ordering': ['-survey'],
            },
        ),
        migrations.CreateModel(
            name='TblAnswerQuestions',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answers', models.ManyToManyField(to='survey_service.TblAnswerOption')),
                ('completed_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_to_question', to='survey_service.TblCompletedSurvey', verbose_name='пройденный опрос')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_to_question', to='survey_service.TblQuestion', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'ответ на вопрос',
                'verbose_name_plural': 'ответы на вопрос',
                'ordering': ['-question'],
            },
        ),
        migrations.AddField(
            model_name='tblansweroption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='survey_service.TblQuestion', verbose_name='вопрос'),
        ),
    ]
